export type StockStatus = 'in_stock' | 'low_stock' | 'out_of_stock'
export type ProductBadge = 'bestseller' | 'new' | 'sale' | null
export type Category = 'Headphones' | 'Keyboards' | 'Monitors'

export interface Review {
  id: string
  author: string
  rating: number
  comment: string
  date: string
}

export interface Product {
  id: string
  name: string
  brand: string
  category: Category
  price: number
  originalPrice?: number
  rating: number
  reviewCount: number
  stock: StockStatus
  badge: ProductBadge
  description: string
  specs: { label: string; value: string }[]
  reviews: Review[]
  relatedIds: string[]
}

export const products: Product[] = [
  {
    id: 'wh-1000xm5',
    name: 'WH-1000XM5',
    brand: 'Sony',
    category: 'Headphones',
    price: 279,
    originalPrice: 349,
    rating: 4.8,
    reviewCount: 2341,
    stock: 'in_stock',
    badge: 'sale',
    description:
      'Industry-leading noise cancellation with two processors and eight microphones. Up to 30 hours of battery life with quick charging support and a lightweight, foldable design.',
    specs: [
      { label: 'Driver size', value: '30mm' },
      { label: 'Frequency response', value: '4 Hz – 40,000 Hz' },
      { label: 'Battery life', value: '30 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.2, 3.5mm' },
      { label: 'Weight', value: '250 g' },
      { label: 'Noise cancellation', value: 'Active (dual processor)' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Alex M.',
        rating: 5,
        comment: 'Best ANC headphones I\'ve ever owned. The noise cancellation is absolutely incredible for flights.',
        date: 'Mar 18, 2025',
      },
      {
        id: 'r2',
        author: 'Priya K.',
        rating: 5,
        comment: 'Sound quality is phenomenal. Worth every penny, especially at this sale price.',
        date: 'Feb 4, 2025',
      },
      {
        id: 'r3',
        author: 'Jordan T.',
        rating: 4,
        comment: 'Excellent headphones. Slightly less comfortable than the XM4 for extended sessions but the ANC upgrade is noticeable.',
        date: 'Jan 22, 2025',
      },
    ],
    relatedIds: ['bose-qc45', 'ath-m50x'],
  },
  {
    id: 'bose-qc45',
    name: 'QuietComfort 45',
    brand: 'Bose',
    category: 'Headphones',
    price: 329,
    rating: 4.6,
    reviewCount: 1872,
    stock: 'low_stock',
    badge: 'bestseller',
    description:
      'Signature Bose sound with TriPort acoustic architecture and high-fidelity audio. Adjustable EQ modes let you switch between full noise cancellation and Aware mode.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Frequency response', value: '20 Hz – 20,000 Hz' },
      { label: 'Battery life', value: '24 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.1, 3.5mm' },
      { label: 'Weight', value: '238 g' },
      { label: 'Noise cancellation', value: 'Active (Quiet & Aware modes)' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Sam R.',
        rating: 5,
        comment: 'Bose sound signature is unmatched. These are incredibly comfortable for all-day wear.',
        date: 'Mar 5, 2025',
      },
      {
        id: 'r2',
        author: 'Mei L.',
        rating: 4,
        comment: 'Great comfort and good ANC. The Sony XM5 has slightly better noise cancellation but these win on comfort.',
        date: 'Feb 14, 2025',
      },
    ],
    relatedIds: ['wh-1000xm5', 'ath-m50x'],
  },
  {
    id: 'ath-m50x',
    name: 'ATH-M50x',
    brand: 'Audio-Technica',
    category: 'Headphones',
    price: 149,
    rating: 4.7,
    reviewCount: 5621,
    stock: 'out_of_stock',
    badge: null,
    description:
      'Professional studio monitor headphones with exceptional clarity across the full frequency range. Collapsible design, detachable cables, and 90° swiveling earcups for one-ear monitoring.',
    specs: [
      { label: 'Driver size', value: '45mm' },
      { label: 'Frequency response', value: '15 Hz – 28,000 Hz' },
      { label: 'Impedance', value: '38 Ω' },
      { label: 'Connectivity', value: '3.5mm (detachable)' },
      { label: 'Weight', value: '285 g' },
      { label: 'Type', value: 'Closed-back, wired' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Chris D.',
        rating: 5,
        comment: 'Studio standard for a reason. Flat response is perfect for mixing. These never leave my desk.',
        date: 'Jan 30, 2025',
      },
      {
        id: 'r2',
        author: 'Nadia V.',
        rating: 4,
        comment: 'Excellent for the price. The clamping force is a bit strong at first but loosens up after a few weeks.',
        date: 'Dec 10, 2024',
      },
    ],
    relatedIds: ['wh-1000xm5', 'bose-qc45'],
  },
  // ── Additional Headphones ──────────────────────────────────────────────────
  {
    id: 'sony-wh1000xm4',
    name: 'WH-1000XM4',
    brand: 'Sony',
    category: 'Headphones',
    price: 199,
    originalPrice: 349,
    rating: 4.7,
    reviewCount: 8921,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Previous-gen flagship ANC headphones with class-leading noise cancellation and 30-hour battery. Multipoint Bluetooth lets you connect two devices simultaneously.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Battery life', value: '30 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.0, 3.5mm' },
      { label: 'Weight', value: '254 g' },
      { label: 'Multipoint', value: '2 devices' },
    ],
    reviews: [
      { id: 'r1', author: 'Dana L.', rating: 5, comment: 'Still the best ANC for the money after the price drop.', date: 'Mar 10, 2025' },
      { id: 'r2', author: 'Felix T.', rating: 5, comment: 'Got these as a step-down from XM5 and they are incredible value.', date: 'Feb 22, 2025' },
    ],
    relatedIds: ['wh-1000xm5', 'bose-qc45'],
  },
  {
    id: 'bose-nc700',
    name: 'Noise Cancelling 700',
    brand: 'Bose',
    category: 'Headphones',
    price: 289,
    originalPrice: 379,
    rating: 4.5,
    reviewCount: 3412,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Elevate your call and music experience with 11 levels of adjustable noise cancellation and 4-mic system for crystal-clear calls. Sleek stainless steel headband.',
    specs: [
      { label: 'Driver size', value: '35mm' },
      { label: 'Battery life', value: '20 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.0, 3.5mm' },
      { label: 'Weight', value: '250 g' },
      { label: 'ANC levels', value: '11 adjustable' },
    ],
    reviews: [
      { id: 'r1', author: 'Sophia H.', rating: 5, comment: 'Microphone quality on calls is leaps ahead of competitors.', date: 'Mar 5, 2025' },
      { id: 'r2', author: 'Noah K.', rating: 4, comment: 'Excellent sound and mic. Battery life not quite as good as Sony.', date: 'Jan 30, 2025' },
    ],
    relatedIds: ['bose-qc45', 'wh-1000xm5'],
  },
  {
    id: 'airpods-max',
    name: 'AirPods Max',
    brand: 'Apple',
    category: 'Headphones',
    price: 449,
    originalPrice: 549,
    rating: 4.6,
    reviewCount: 5872,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Apple-designed dynamic driver delivers high-fidelity audio with computational audio and custom ANC. Seamless integration with Apple devices via H1 chip.',
    specs: [
      { label: 'Driver size', value: '40mm (Apple custom)' },
      { label: 'Battery life', value: '20 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.0, Lightning' },
      { label: 'Weight', value: '385 g' },
      { label: 'Chip', value: 'Apple H1 (×2)' },
    ],
    reviews: [
      { id: 'r1', author: 'Chloe R.', rating: 5, comment: 'The sound quality in Apple ecosystem is unmatched. Spatial audio is a revelation.', date: 'Feb 28, 2025' },
      { id: 'r2', author: 'Ethan M.', rating: 4, comment: 'Premium product. Heavy but comfortable. Worth it if you are deep in Apple ecosystem.', date: 'Jan 15, 2025' },
    ],
    relatedIds: ['bose-nc700', 'wh-1000xm5'],
  },
  {
    id: 'sennheiser-momentum4',
    name: 'Momentum 4 Wireless',
    brand: 'Sennheiser',
    category: 'Headphones',
    price: 249,
    originalPrice: 349,
    rating: 4.7,
    reviewCount: 2104,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Up to 60 hours of playtime with adaptive noise cancellation and Sennheiser Sound Signature. Foldable design with plush leatherette ear pads for all-day comfort.',
    specs: [
      { label: 'Driver size', value: '42mm' },
      { label: 'Battery life', value: '60 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.2, 3.5mm' },
      { label: 'Weight', value: '293 g' },
      { label: 'ANC', value: 'Adaptive' },
    ],
    reviews: [
      { id: 'r1', author: 'Anna P.', rating: 5, comment: '60 hours of battery is insane. Forgot to charge them for 2 weeks and they still had juice.', date: 'Mar 20, 2025' },
      { id: 'r2', author: 'Luca B.', rating: 5, comment: 'Sennheiser tuning sounds incredible. More natural than Sony or Bose.', date: 'Feb 11, 2025' },
    ],
    relatedIds: ['sennheiser-hd660s2', 'bose-qc45'],
  },
  {
    id: 'sennheiser-hd660s2',
    name: 'HD 660 S2',
    brand: 'Sennheiser',
    category: 'Headphones',
    price: 299,
    rating: 4.9,
    reviewCount: 1243,
    stock: 'in_stock',
    badge: 'new',
    description: 'Open-back audiophile headphones with newly tuned bass response and 300 Ω high-impedance transducers. Reference-level listening for serious music enthusiasts.',
    specs: [
      { label: 'Driver size', value: '38mm' },
      { label: 'Impedance', value: '300 Ω' },
      { label: 'Frequency response', value: '8 Hz – 41,500 Hz' },
      { label: 'Connectivity', value: '6.35mm, 4.4mm balanced' },
      { label: 'Type', value: 'Open-back, wired' },
    ],
    reviews: [
      { id: 'r1', author: 'Victor S.', rating: 5, comment: 'These are end-game open-back headphones. Incredible soundstage and separation.', date: 'Mar 12, 2025' },
      { id: 'r2', author: 'Iris C.', rating: 5, comment: 'Need an amp to drive properly but the sound rewards the effort.', date: 'Feb 5, 2025' },
    ],
    relatedIds: ['beyerdynamic-dt900', 'ath-m50x'],
  },
  {
    id: 'beyerdynamic-dt900',
    name: 'DT 900 Pro X',
    brand: 'Beyerdynamic',
    category: 'Headphones',
    price: 299,
    rating: 4.8,
    reviewCount: 1087,
    stock: 'in_stock',
    badge: null,
    description: 'Open-back studio reference headphones with STELLAR.45 driver for accurate and transparent sound. Ideal for mixing, mastering, and critical listening in the studio.',
    specs: [
      { label: 'Driver', value: 'STELLAR.45 (45mm)' },
      { label: 'Impedance', value: '48 Ω' },
      { label: 'Frequency response', value: '5 Hz – 40,000 Hz' },
      { label: 'Connectivity', value: '3.5mm + 6.35mm adapter' },
      { label: 'Type', value: 'Open-back, wired' },
    ],
    reviews: [
      { id: 'r1', author: 'Marcus W.', rating: 5, comment: 'My new studio reference. Incredibly flat and detailed response.', date: 'Mar 8, 2025' },
      { id: 'r2', author: 'Sarah J.', rating: 5, comment: 'Replaced my ATH-M50x with these. No going back.', date: 'Jan 20, 2025' },
    ],
    relatedIds: ['sennheiser-hd660s2', 'ath-m50x'],
  },
  {
    id: 'beyerdynamic-dt770',
    name: 'DT 770 Pro',
    brand: 'Beyerdynamic',
    category: 'Headphones',
    price: 149,
    rating: 4.8,
    reviewCount: 9234,
    stock: 'in_stock',
    badge: 'bestseller',
    description: 'Closed-back studio headphones trusted by professionals for over 30 years. The 80 Ω version offers the perfect balance for studio use with most interfaces.',
    specs: [
      { label: 'Driver size', value: '45mm' },
      { label: 'Impedance', value: '80 Ω' },
      { label: 'Frequency response', value: '5 Hz – 35,000 Hz' },
      { label: 'Connectivity', value: '3.5mm + 6.35mm adapter' },
      { label: 'Type', value: 'Closed-back, wired' },
    ],
    reviews: [
      { id: 'r1', author: 'Derek O.', rating: 5, comment: 'The industry standard closed-back. I have owned 3 pairs over 15 years.', date: 'Mar 1, 2025' },
      { id: 'r2', author: 'Mia F.', rating: 5, comment: 'Bought for podcasting and they are perfect. Bass-forward but not muddy.', date: 'Feb 14, 2025' },
    ],
    relatedIds: ['ath-m50x', 'beyerdynamic-dt900'],
  },
  {
    id: 'jabra-evolve2-85',
    name: 'Evolve2 85',
    brand: 'Jabra',
    category: 'Headphones',
    price: 379,
    rating: 4.6,
    reviewCount: 1876,
    stock: 'in_stock',
    badge: null,
    description: 'Professional UC-certified wireless headset with 10 microphones and advanced ANC. Built for serious hybrid workers with 37-hour battery and Jabra MultiSensor Voice technology.',
    specs: [
      { label: 'Microphones', value: '10 total' },
      { label: 'Battery life', value: '37 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.0, USB-A/C dongle' },
      { label: 'Weight', value: '340 g' },
      { label: 'Certification', value: 'Microsoft Teams, Zoom' },
    ],
    reviews: [
      { id: 'r1', author: 'Paul G.', rating: 5, comment: 'Best headset for WFH. Call quality blows everyone else away on Teams calls.', date: 'Mar 18, 2025' },
      { id: 'r2', author: 'Karen N.', rating: 4, comment: 'Professional grade. The ANC is very good and battery life is best in class.', date: 'Feb 1, 2025' },
    ],
    relatedIds: ['jabra-evolve2-65', 'bose-nc700'],
  },
  {
    id: 'jabra-evolve2-65',
    name: 'Evolve2 65',
    brand: 'Jabra',
    category: 'Headphones',
    price: 249,
    rating: 4.5,
    reviewCount: 2341,
    stock: 'in_stock',
    badge: null,
    description: 'Wireless headset with engineered microphone boom and 37-hour battery. Passive noise cancellation and professional audio tuning for focused work from anywhere.',
    specs: [
      { label: 'Microphones', value: '3-mic call technology' },
      { label: 'Battery life', value: '37 hrs' },
      { label: 'Connectivity', value: 'Bluetooth 5.0, USB-A dongle' },
      { label: 'Weight', value: '151 g' },
      { label: 'Certification', value: 'Microsoft Teams' },
    ],
    reviews: [
      { id: 'r1', author: 'Tina R.', rating: 5, comment: 'Perfect call headset. Lightweight and the battery is incredible.', date: 'Feb 20, 2025' },
      { id: 'r2', author: 'Ben M.', rating: 4, comment: 'Great for work calls. Not the best for casual music listening.', date: 'Jan 12, 2025' },
    ],
    relatedIds: ['jabra-evolve2-85', 'bose-qc45'],
  },
  {
    id: 'beats-studio-pro',
    name: 'Studio Pro',
    brand: 'Beats',
    category: 'Headphones',
    price: 199,
    originalPrice: 349,
    rating: 4.4,
    reviewCount: 3201,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Personalized Spatial Audio with dynamic head tracking and four listening modes. USB-C and 3.5mm wired listening with lossless audio. Up to 40 hours of battery.',
    specs: [
      { label: 'Battery life', value: '40 hrs (ANC off)' },
      { label: 'Connectivity', value: 'Bluetooth 5.3, USB-C, 3.5mm' },
      { label: 'Weight', value: '260 g' },
      { label: 'Chip', value: 'Apple compatible' },
      { label: 'Lossless', value: 'Via USB-C wired' },
    ],
    reviews: [
      { id: 'r1', author: 'Jay C.', rating: 5, comment: 'Great for Android and iPhone users alike. 40-hour battery is huge.', date: 'Mar 22, 2025' },
      { id: 'r2', author: 'Lisa T.', rating: 4, comment: 'Sound is punchy and fun. ANC is decent for the price.', date: 'Feb 10, 2025' },
    ],
    relatedIds: ['beats-studio3', 'bose-qc45'],
  },
  {
    id: 'beats-studio3',
    name: 'Studio3 Wireless',
    brand: 'Beats',
    category: 'Headphones',
    price: 169,
    originalPrice: 349,
    rating: 4.3,
    reviewCount: 12087,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Pure Adaptive Noise Cancelling headphones with Apple W1 chip for fast pairing and 22-hour battery. A classic designed for the street with bold style.',
    specs: [
      { label: 'Battery life', value: '22 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 4.0, 3.5mm' },
      { label: 'Weight', value: '260 g' },
      { label: 'Chip', value: 'Apple W1' },
    ],
    reviews: [
      { id: 'r1', author: 'Tyler K.', rating: 4, comment: 'Great at this sale price. Sound is fun, ANC is good enough for commuting.', date: 'Mar 15, 2025' },
      { id: 'r2', author: 'Aisha W.', rating: 4, comment: 'Iconic look and decent sound. Not audiophile but excellent for the price.', date: 'Feb 3, 2025' },
    ],
    relatedIds: ['beats-studio-pro', 'bose-qc45'],
  },
  {
    id: 'bo-beoplay-h95',
    name: 'Beoplay H95',
    brand: 'Bang & Olufsen',
    category: 'Headphones',
    price: 649,
    rating: 4.7,
    reviewCount: 521,
    stock: 'in_stock',
    badge: null,
    description: 'Flagship luxury wireless headphones crafted from titanium and lambskin leather. Adaptive ANC, 38-hour battery, and 10mm precision-machined titanium drivers.',
    specs: [
      { label: 'Driver', value: '40mm titanium' },
      { label: 'Battery life', value: '38 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.1, 3.5mm, USB-C' },
      { label: 'Weight', value: '326 g' },
      { label: 'Materials', value: 'Titanium, lambskin leather' },
    ],
    reviews: [
      { id: 'r1', author: 'Henri V.', rating: 5, comment: 'The most beautiful headphones I have ever owned. Sound matches the design.', date: 'Feb 25, 2025' },
      { id: 'r2', author: 'Claire D.', rating: 5, comment: 'A true luxury item. The case alone is worth writing home about.', date: 'Jan 8, 2025' },
    ],
    relatedIds: ['bo-beoplay-h9i', 'airpods-max'],
  },
  {
    id: 'bo-beoplay-h9i',
    name: 'Beoplay H9i',
    brand: 'Bang & Olufsen',
    category: 'Headphones',
    price: 349,
    originalPrice: 499,
    rating: 4.5,
    reviewCount: 743,
    stock: 'low_stock',
    badge: 'sale',
    description: 'Premium over-ear headphones with touch interface controls, transparent hearing mode, and natural lambskin ear cushions. Warm, musical B&O sound signature.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Battery life', value: '25 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 4.2, 3.5mm' },
      { label: 'Weight', value: '335 g' },
      { label: 'Controls', value: 'Touch-sensitive ear cup' },
    ],
    reviews: [
      { id: 'r1', author: 'Philippe N.', rating: 5, comment: 'Gorgeous design and wonderful sound. The touch controls are a delight.', date: 'Mar 7, 2025' },
      { id: 'r2', author: 'Ines R.', rating: 4, comment: 'Beautiful but the ANC lags behind Sony and Bose at this price.', date: 'Jan 25, 2025' },
    ],
    relatedIds: ['bo-beoplay-h95', 'airpods-max'],
  },
  {
    id: 'anker-q45',
    name: 'Soundcore Q45',
    brand: 'Anker',
    category: 'Headphones',
    price: 59,
    originalPrice: 79,
    rating: 4.4,
    reviewCount: 18923,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Budget-friendly ANC headphones with 50-hour battery, foldable design, and LDAC Hi-Res audio. Multi-mode ANC adapts to different environments automatically.',
    specs: [
      { label: 'Battery life', value: '50 hrs (ANC off)' },
      { label: 'Connectivity', value: 'Bluetooth 5.3, 3.5mm' },
      { label: 'Weight', value: '255 g' },
      { label: 'Codec', value: 'LDAC, AAC, SBC' },
      { label: 'ANC', value: 'Multi-mode adaptive' },
    ],
    reviews: [
      { id: 'r1', author: 'Kevin L.', rating: 5, comment: 'Absolutely insane value. ANC rivals headphones 3x the price.', date: 'Mar 28, 2025' },
      { id: 'r2', author: 'Sophie T.', rating: 4, comment: 'Perfect budget ANC headphones. 50-hour battery is mind-blowing.', date: 'Feb 16, 2025' },
    ],
    relatedIds: ['anker-q35', 'jbl-live770'],
  },
  {
    id: 'anker-q35',
    name: 'Soundcore Q35',
    brand: 'Anker',
    category: 'Headphones',
    price: 49,
    rating: 4.3,
    reviewCount: 22041,
    stock: 'in_stock',
    badge: 'bestseller',
    description: 'Hybrid active noise cancellation removes up to 95% of ambient noise. Hi-Res 40mm audio drivers with BassUp technology. 40-hour playtime with fast charging.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Battery life', value: '40 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.0, 3.5mm' },
      { label: 'Weight', value: '238 g' },
      { label: 'ANC', value: 'Hybrid (feed-forward + feedback)' },
    ],
    reviews: [
      { id: 'r1', author: 'Omar N.', rating: 5, comment: 'Best sub-$50 ANC headphones by a mile. Bought as backup and now use them daily.', date: 'Mar 5, 2025' },
      { id: 'r2', author: 'Priya S.', rating: 4, comment: 'Great ANC for commuting. Sound quality is surprisingly good.', date: 'Jan 30, 2025' },
    ],
    relatedIds: ['anker-q45', 'jbl-live660'],
  },
  {
    id: 'jbl-live770',
    name: 'Live 770NC',
    brand: 'JBL',
    category: 'Headphones',
    price: 129,
    originalPrice: 199,
    rating: 4.4,
    reviewCount: 4312,
    stock: 'in_stock',
    badge: 'sale',
    description: 'True Adaptive ANC with VoiceAware and 65-hour total battery life. Wireless multi-point connection and JBL Personi-Fi personalized sound profile setup.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Battery life', value: '50 hrs (ANC on), 65 hrs total' },
      { label: 'Connectivity', value: 'Bluetooth 5.3, 3.5mm' },
      { label: 'Weight', value: '256 g' },
      { label: 'ANC', value: 'True Adaptive' },
    ],
    reviews: [
      { id: 'r1', author: 'Rachel M.', rating: 5, comment: 'The 65-hour battery blew me away. JBL sound signature is perfect for pop and EDM.', date: 'Mar 11, 2025' },
      { id: 'r2', author: 'Sam B.', rating: 4, comment: 'Great ANC and value. The app is a bit clunky but the hardware is stellar.', date: 'Feb 18, 2025' },
    ],
    relatedIds: ['jbl-live660', 'anker-q45'],
  },
  {
    id: 'jbl-live660',
    name: 'Live 660NC',
    brand: 'JBL',
    category: 'Headphones',
    price: 79,
    originalPrice: 129,
    rating: 4.3,
    reviewCount: 6201,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Wireless noise-cancelling headphones with up to 70 hours playtime. JBL Signature Sound with Google Fast Pair and Alexa built-in support.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Battery life', value: '50 hrs (ANC on), 70 hrs total' },
      { label: 'Connectivity', value: 'Bluetooth 5.0, 3.5mm' },
      { label: 'Weight', value: '228 g' },
    ],
    reviews: [
      { id: 'r1', author: 'Dan O.', rating: 4, comment: 'Excellent budget ANC pick. JBL bass is fun and engaging.', date: 'Mar 3, 2025' },
      { id: 'r2', author: 'Yuki T.', rating: 4, comment: '70 hours battery is unreal. Comfortable for long sessions.', date: 'Feb 8, 2025' },
    ],
    relatedIds: ['jbl-live770', 'anker-q35'],
  },
  {
    id: 'skullcandy-crusher-evo',
    name: 'Crusher Evo',
    brand: 'Skullcandy',
    category: 'Headphones',
    price: 99,
    originalPrice: 149,
    rating: 4.3,
    reviewCount: 7821,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Adjustable sensory bass with Personal Sound powered by Audiodo. Indy Fuel wireless charging with 40-hour battery and a built-in tile tracker.',
    specs: [
      { label: 'Battery life', value: '40 hrs' },
      { label: 'Connectivity', value: 'Bluetooth 5.0, 3.5mm' },
      { label: 'Weight', value: '296 g' },
      { label: 'Bass', value: 'Adjustable haptic bass' },
    ],
    reviews: [
      { id: 'r1', author: 'Zach P.', rating: 5, comment: 'The adjustable bass is addictive. Perfect for bass-heavy genres.', date: 'Feb 28, 2025' },
      { id: 'r2', author: 'Nadia H.', rating: 4, comment: 'Fun headphones. Not audiophile but great for gym and commuting.', date: 'Jan 19, 2025' },
    ],
    relatedIds: ['skullcandy-hesh-evo', 'anker-q45'],
  },
  {
    id: 'skullcandy-hesh-evo',
    name: 'Hesh Evo',
    brand: 'Skullcandy',
    category: 'Headphones',
    price: 49,
    rating: 4.1,
    reviewCount: 9012,
    stock: 'in_stock',
    badge: null,
    description: 'Wireless headphones with Supreme Sound and a 36-hour battery. Rapid Charge provides 2 hours of play from a 10-minute charge. Soft-touch finish and foldable design.',
    specs: [
      { label: 'Battery life', value: '36 hrs' },
      { label: 'Connectivity', value: 'Bluetooth 5.0' },
      { label: 'Weight', value: '190 g' },
      { label: 'Fast charge', value: '10 min → 2 hrs' },
    ],
    reviews: [
      { id: 'r1', author: 'Carla V.', rating: 4, comment: 'Great budget option. Comfortable and the sound is decent.', date: 'Mar 9, 2025' },
      { id: 'r2', author: 'Tom A.', rating: 4, comment: 'Bought for my teenager and they love it.', date: 'Feb 2, 2025' },
    ],
    relatedIds: ['skullcandy-crusher-evo', 'anker-q35'],
  },
  {
    id: 'ath-m40x',
    name: 'ATH-M40x',
    brand: 'Audio-Technica',
    category: 'Headphones',
    price: 99,
    rating: 4.6,
    reviewCount: 7234,
    stock: 'in_stock',
    badge: null,
    description: 'Professional monitor headphones with flat, accurate sound and 90° swiveling earcups. Detachable cables and fold-flat design for portability and storage.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Frequency response', value: '15 Hz – 24,000 Hz' },
      { label: 'Impedance', value: '35 Ω' },
      { label: 'Connectivity', value: '3.5mm (detachable)' },
      { label: 'Type', value: 'Closed-back, wired' },
    ],
    reviews: [
      { id: 'r1', author: 'Sam K.', rating: 5, comment: 'ATH-M50x on a budget. Flat response is perfect for mixing on the go.', date: 'Mar 14, 2025' },
      { id: 'r2', author: 'Grace L.', rating: 4, comment: 'Solid monitor headphones. Better value than the M50x for casual use.', date: 'Jan 23, 2025' },
    ],
    relatedIds: ['ath-m50x', 'beyerdynamic-dt770'],
  },
  {
    id: 'ath-adx5000',
    name: 'ATH-ADX5000',
    brand: 'Audio-Technica',
    category: 'Headphones',
    price: 1099,
    rating: 4.9,
    reviewCount: 312,
    stock: 'low_stock',
    badge: null,
    description: 'Flagship open-back audiophile headphones with magnesium alloy baffle and A2DC connector. 58mm drivers with tungsten-coated diaphragms for uncompromising sound fidelity.',
    specs: [
      { label: 'Driver size', value: '58mm' },
      { label: 'Impedance', value: '420 Ω' },
      { label: 'Frequency response', value: '5 Hz – 50,000 Hz' },
      { label: 'Connectivity', value: 'A2DC, 4.4mm, XLR-4' },
      { label: 'Type', value: 'Open-back, wired' },
    ],
    reviews: [
      { id: 'r1', author: 'James V.', rating: 5, comment: 'The pinnacle of headphone design. Imaging and resolution are in a different league.', date: 'Feb 18, 2025' },
      { id: 'r2', author: 'Yoko N.', rating: 5, comment: 'Endgame headphones. Once you hear these you cannot go back.', date: 'Jan 4, 2025' },
    ],
    relatedIds: ['sennheiser-hd660s2', 'beyerdynamic-dt900'],
  },
  {
    id: 'plantronics-voyager',
    name: 'Voyager Focus 2',
    brand: 'Poly',
    category: 'Headphones',
    price: 219,
    rating: 4.4,
    reviewCount: 2109,
    stock: 'in_stock',
    badge: null,
    description: 'Advanced ANC headset with 8-mic hybrid noise cancellation for calls. Smart sensor auto-pauses music when headset is removed. USB-C charging with 19-hour battery.',
    specs: [
      { label: 'Microphones', value: '8 total (hybrid ANC)' },
      { label: 'Battery life', value: '19 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.2, USB-C dongle' },
      { label: 'Weight', value: '200 g' },
      { label: 'Certification', value: 'Microsoft Teams, Zoom' },
    ],
    reviews: [
      { id: 'r1', author: 'Henry O.', rating: 5, comment: 'Best mic quality for remote work meetings. Crystal clear calls every time.', date: 'Mar 16, 2025' },
      { id: 'r2', author: 'Emma R.', rating: 4, comment: 'Excellent work headset. Smart sensors are very reliable.', date: 'Feb 9, 2025' },
    ],
    relatedIds: ['jabra-evolve2-65', 'jabra-evolve2-85'],
  },
  {
    id: 'hyperx-cloud-alpha',
    name: 'Cloud Alpha Wireless',
    brand: 'HyperX',
    category: 'Headphones',
    price: 179,
    originalPrice: 199,
    rating: 4.7,
    reviewCount: 4523,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Gaming headset with an astounding 300-hour battery life and dual-chamber driver design. Detachable noise-cancelling microphone with Discord and TeamSpeak certification.',
    specs: [
      { label: 'Driver size', value: '40mm (dual-chamber)' },
      { label: 'Battery life', value: '300 hrs' },
      { label: 'Connectivity', value: '2.4GHz wireless, 3.5mm' },
      { label: 'Weight', value: '335 g' },
      { label: 'Mic', value: 'Detachable, noise-cancelling' },
    ],
    reviews: [
      { id: 'r1', author: 'Jake S.', rating: 5, comment: '300-hour battery is not a typo. I charge it once a month.', date: 'Mar 20, 2025' },
      { id: 'r2', author: 'Lily F.', rating: 5, comment: 'Best wireless gaming headset. Comfortable for 8-hour sessions.', date: 'Feb 25, 2025' },
    ],
    relatedIds: ['hyperx-cloud-orbit', 'steelseries-arctis-7'],
  },
  {
    id: 'hyperx-cloud-orbit',
    name: 'Cloud Orbit S',
    brand: 'HyperX',
    category: 'Headphones',
    price: 149,
    originalPrice: 329,
    rating: 4.5,
    reviewCount: 1892,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Gaming and studio headset with Waves Nx head-tracking 3D audio. 100mm planar magnetic drivers deliver an unprecedented soundstage for immersive gaming.',
    specs: [
      { label: 'Driver', value: '100mm planar magnetic' },
      { label: 'Connectivity', value: 'USB-A, 3.5mm' },
      { label: 'Weight', value: '392 g' },
      { label: '3D audio', value: 'Waves Nx head-tracking' },
      { label: 'Type', value: 'Closed-back, wired' },
    ],
    reviews: [
      { id: 'r1', author: 'Dave P.', rating: 5, comment: 'Planar magnetic drivers in a gaming headset at this price. Steal of the decade.', date: 'Mar 1, 2025' },
      { id: 'r2', author: 'Naomi J.', rating: 4, comment: 'Incredible detail retrieval. Heavy but worth it for the sound.', date: 'Jan 15, 2025' },
    ],
    relatedIds: ['hyperx-cloud-alpha', 'steelseries-arctis-7'],
  },
  {
    id: 'steelseries-arctis-7',
    name: 'Arctis 7+',
    brand: 'SteelSeries',
    category: 'Headphones',
    price: 149,
    originalPrice: 169,
    rating: 4.6,
    reviewCount: 5621,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Wireless gaming headset with 30-hour battery and ChatMix dial for blending game and chat audio. ClearCast bidirectional microphone with Discord certification.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Battery life', value: '30 hrs' },
      { label: 'Connectivity', value: '2.4GHz USB, 3.5mm' },
      { label: 'Weight', value: '352 g' },
      { label: 'Mic', value: 'ClearCast bidirectional, retractable' },
    ],
    reviews: [
      { id: 'r1', author: 'Aaron W.', rating: 5, comment: 'Best gaming headset for the money. ChatMix dial is genius.', date: 'Mar 12, 2025' },
      { id: 'r2', author: 'Brianna C.', rating: 5, comment: 'Comfortable headband and great microphone quality.', date: 'Feb 7, 2025' },
    ],
    relatedIds: ['hyperx-cloud-alpha', 'razer-blackshark-v2'],
  },
  {
    id: 'razer-blackshark-v2',
    name: 'BlackShark V2 Pro',
    brand: 'Razer',
    category: 'Headphones',
    price: 179,
    rating: 4.5,
    reviewCount: 3879,
    stock: 'in_stock',
    badge: null,
    description: 'THX-certified wireless gaming headset with TriForce Titanium 50mm drivers split into treble, mid, and bass sections. HyperSpeed Wireless with sub-40ms latency.',
    specs: [
      { label: 'Driver size', value: '50mm (TriForce Titanium)' },
      { label: 'Battery life', value: '70 hrs' },
      { label: 'Connectivity', value: 'HyperSpeed 2.4GHz, Bluetooth, 3.5mm' },
      { label: 'Weight', value: '320 g' },
      { label: 'Certification', value: 'THX Spatial Audio' },
    ],
    reviews: [
      { id: 'r1', author: 'Kyle B.', rating: 5, comment: 'THX certification is not marketing. The soundstage for FPS is incredible.', date: 'Mar 18, 2025' },
      { id: 'r2', author: 'Megan S.', rating: 4, comment: '70-hour battery and great sound. My go-to for console and PC.', date: 'Feb 20, 2025' },
    ],
    relatedIds: ['steelseries-arctis-7', 'hyperx-cloud-alpha'],
  },
  {
    id: 'logitech-g535',
    name: 'G535 Lightspeed',
    brand: 'Logitech',
    category: 'Headphones',
    price: 99,
    originalPrice: 129,
    rating: 4.4,
    reviewCount: 2890,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Ultra-lightweight 236g wireless gaming headset with 33-hour battery. Discrete design makes it suitable for work and gaming. Flip-to-mute microphone with Discord certification.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Battery life', value: '33 hrs' },
      { label: 'Connectivity', value: 'Lightspeed 2.4GHz, 3.5mm' },
      { label: 'Weight', value: '236 g (lightest in class)' },
      { label: 'Mic', value: 'Flip-to-mute, Discord certified' },
    ],
    reviews: [
      { id: 'r1', author: 'Finn D.', rating: 5, comment: 'So light I forget I am wearing it. Great for long gaming nights.', date: 'Mar 4, 2025' },
      { id: 'r2', author: 'Aria K.', rating: 4, comment: 'Looks professional enough for work calls and sounds great for gaming.', date: 'Feb 1, 2025' },
    ],
    relatedIds: ['steelseries-arctis-7', 'hyperx-cloud-alpha'],
  },
  {
    id: 'corsair-hs80',
    name: 'HS80 RGB Wireless',
    brand: 'Corsair',
    category: 'Headphones',
    price: 129,
    rating: 4.5,
    reviewCount: 3201,
    stock: 'in_stock',
    badge: null,
    description: 'Wireless gaming headset with Dolby Atmos and iCUE software integration. Memory foam ear pads and premium aluminum fork construction. 60-hour battery.',
    specs: [
      { label: 'Driver size', value: '50mm' },
      { label: 'Battery life', value: '60 hrs' },
      { label: 'Connectivity', value: 'Slipstream 2.4GHz, 3.5mm' },
      { label: 'Weight', value: '340 g' },
      { label: 'Audio', value: 'Dolby Atmos' },
    ],
    reviews: [
      { id: 'r1', author: 'Hunter L.', rating: 5, comment: '60-hour battery and Dolby Atmos. One of the best gaming headsets under $150.', date: 'Mar 22, 2025' },
      { id: 'r2', author: 'Zoe C.', rating: 4, comment: 'Very comfortable. Memory foam is excellent. iCUE integration is a bonus.', date: 'Feb 14, 2025' },
    ],
    relatedIds: ['logitech-g535', 'steelseries-arctis-7'],
  },
  {
    id: 'astro-a50',
    name: 'A50 Wireless + Base Station',
    brand: 'ASTRO Gaming',
    category: 'Headphones',
    price: 299,
    rating: 4.4,
    reviewCount: 2134,
    stock: 'in_stock',
    badge: null,
    description: 'Premium wireless gaming headset with charging base station. Dolby Audio and Pro EQ presets. Automatically charges when placed on the dock and powers on when lifted.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Battery life', value: '15 hrs' },
      { label: 'Connectivity', value: '5GHz wireless base station, optical, 3.5mm' },
      { label: 'Weight', value: '380 g' },
      { label: 'Dock', value: 'Auto charge + power on' },
    ],
    reviews: [
      { id: 'r1', author: 'Brett M.', rating: 5, comment: 'The dock system is so convenient. Drop it on, it charges and turns off automatically.', date: 'Feb 27, 2025' },
      { id: 'r2', author: 'Jess A.', rating: 4, comment: 'Great sound and super convenient dock. Battery life a bit short at 15 hours.', date: 'Jan 20, 2025' },
    ],
    relatedIds: ['razer-blackshark-v2', 'hyperx-cloud-alpha'],
  },
  {
    id: 'shure-srh840a',
    name: 'SRH840A',
    brand: 'Shure',
    category: 'Headphones',
    price: 149,
    rating: 4.7,
    reviewCount: 1432,
    stock: 'in_stock',
    badge: null,
    description: 'Professional monitoring headphones with 40mm drivers for accurate, full-range audio reproduction. Padded headband, collapsible single-ear monitoring, and replaceable ear pads.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Frequency response', value: '5 Hz – 25,000 Hz' },
      { label: 'Impedance', value: '44 Ω' },
      { label: 'Connectivity', value: '3.5mm + 6.35mm adapter' },
      { label: 'Type', value: 'Closed-back, wired' },
    ],
    reviews: [
      { id: 'r1', author: 'Mike E.', rating: 5, comment: 'Perfect monitoring headphones. Very neutral and honest sound.', date: 'Mar 8, 2025' },
      { id: 'r2', author: 'Kate B.', rating: 5, comment: 'Replaced my M40x with these. The clarity is a step up.', date: 'Feb 22, 2025' },
    ],
    relatedIds: ['ath-m50x', 'ath-m40x'],
  },
  {
    id: 'shure-aonic50',
    name: 'AONIC 50 Gen 2',
    brand: 'Shure',
    category: 'Headphones',
    price: 299,
    rating: 4.7,
    reviewCount: 1087,
    stock: 'in_stock',
    badge: null,
    description: 'Premium wireless noise-cancelling headphones with Shure signature audio quality. Adjustable ANC and environment modes, USB-C charging, and up to 30-hour battery life.',
    specs: [
      { label: 'Driver size', value: '50mm' },
      { label: 'Battery life', value: '30 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.0, USB-C, 3.5mm' },
      { label: 'Weight', value: '290 g' },
      { label: 'Codec', value: 'aptX Adaptive, AAC' },
    ],
    reviews: [
      { id: 'r1', author: 'Nate F.', rating: 5, comment: 'Shure audio quality in a wireless package. The most transparent ANC headphones I have tried.', date: 'Mar 10, 2025' },
      { id: 'r2', author: 'Wendy H.', rating: 4, comment: 'Excellent headphones. ANC is not as strong as Sony but sound quality is superior.', date: 'Feb 5, 2025' },
    ],
    relatedIds: ['sennheiser-momentum4', 'bose-nc700'],
  },
  {
    id: 'marshall-major5',
    name: 'Major V',
    brand: 'Marshall',
    category: 'Headphones',
    price: 149,
    rating: 4.4,
    reviewCount: 2876,
    stock: 'in_stock',
    badge: 'new',
    description: 'Iconic on-ear headphones with 100-hour battery, Marshall signature rock sound, and foldable design. Multi-directional control knob for easy track and volume adjustment.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Battery life', value: '100 hrs' },
      { label: 'Connectivity', value: 'Bluetooth 5.3, 3.5mm' },
      { label: 'Weight', value: '190 g' },
      { label: 'Controls', value: 'Multi-directional knob' },
    ],
    reviews: [
      { id: 'r1', author: 'Rob S.', rating: 5, comment: '100-hour battery is the headline. Marshall aesthetic is iconic.', date: 'Mar 25, 2025' },
      { id: 'r2', author: 'Erin J.', rating: 4, comment: 'On-ear fit takes getting used to but the sound is warm and musical.', date: 'Mar 1, 2025' },
    ],
    relatedIds: ['marshall-midanc', 'skullcandy-crusher-evo'],
  },
  {
    id: 'marshall-midanc',
    name: 'Mid ANC',
    brand: 'Marshall',
    category: 'Headphones',
    price: 169,
    originalPrice: 299,
    rating: 4.2,
    reviewCount: 1654,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Over-ear noise-cancelling headphones with Marshall sound and retro aesthetic. Active noise cancellation and monitor mode. Wired or wireless operation.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Battery life', value: '20 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.0, 3.5mm' },
      { label: 'Weight', value: '285 g' },
    ],
    reviews: [
      { id: 'r1', author: 'Chris M.', rating: 4, comment: 'Marshall sound in an ANC package. The retro look is stunning.', date: 'Feb 15, 2025' },
      { id: 'r2', author: 'Dana K.', rating: 4, comment: 'Good ANC and iconic style. Battery life a bit short.', date: 'Jan 10, 2025' },
    ],
    relatedIds: ['marshall-major5', 'beats-studio-pro'],
  },
  {
    id: 'sony-mdr-z7m2',
    name: 'MDR-Z7M2',
    brand: 'Sony',
    category: 'Headphones',
    price: 699,
    rating: 4.8,
    reviewCount: 423,
    stock: 'low_stock',
    badge: null,
    description: 'Hi-Res wired headphones with 70mm HD driver units and silver-coated 4N OFC cable. Balanced and unbalanced connections for audiophile listening.',
    specs: [
      { label: 'Driver size', value: '70mm' },
      { label: 'Frequency response', value: '5 Hz – 120,000 Hz' },
      { label: 'Impedance', value: '70 Ω' },
      { label: 'Connectivity', value: '4.4mm balanced, 3.5mm' },
      { label: 'Type', value: 'Closed-back, wired' },
    ],
    reviews: [
      { id: 'r1', author: 'Ken Y.', rating: 5, comment: '70mm drivers are something else. The bass extension and detail are phenomenal.', date: 'Feb 10, 2025' },
      { id: 'r2', author: 'Tara B.', rating: 5, comment: 'Endgame closed-back. Nothing sounds quite like this.', date: 'Dec 20, 2024' },
    ],
    relatedIds: ['ath-adx5000', 'sennheiser-hd660s2'],
  },
  {
    id: 'sony-wh-ch720n',
    name: 'WH-CH720N',
    brand: 'Sony',
    category: 'Headphones',
    price: 99,
    originalPrice: 149,
    rating: 4.4,
    reviewCount: 5601,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Lightweight 192g ANC headphones with 35-hour battery and Integrated Processor V1. Quick Attention mode and Speak-to-Chat feature for hands-free convenience.',
    specs: [
      { label: 'Driver size', value: '30mm' },
      { label: 'Battery life', value: '35 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.2, 3.5mm' },
      { label: 'Weight', value: '192 g' },
      { label: 'ANC', value: 'Integrated Processor V1' },
    ],
    reviews: [
      { id: 'r1', author: 'Hanna P.', rating: 5, comment: 'Best lightweight ANC headphones. So light I barely feel them.', date: 'Mar 19, 2025' },
      { id: 'r2', author: 'Jacob R.', rating: 4, comment: 'Great daily drivers. ANC is solid for the price.', date: 'Feb 12, 2025' },
    ],
    relatedIds: ['wh-1000xm4', 'anker-q45'],
  },
  {
    id: 'bose-qc-ultra',
    name: 'QuietComfort Ultra',
    brand: 'Bose',
    category: 'Headphones',
    price: 349,
    rating: 4.7,
    reviewCount: 3892,
    stock: 'in_stock',
    badge: 'new',
    description: 'Bose\'s most premium ANC headphones with Immersive Audio spatial sound. CustomTune calibration personalizes the sound for your unique ear shape. 24-hour battery.',
    specs: [
      { label: 'Driver size', value: '35mm' },
      { label: 'Battery life', value: '24 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.3, USB-C, 3.5mm' },
      { label: 'Weight', value: '250 g' },
      { label: 'Feature', value: 'CustomTune personalization' },
    ],
    reviews: [
      { id: 'r1', author: 'Olivia M.', rating: 5, comment: 'The Immersive Audio feature is a genuine wow moment. Best Bose yet.', date: 'Mar 28, 2025' },
      { id: 'r2', author: 'Nathan S.', rating: 5, comment: 'CustomTune personalizes the sound so well. Worth the premium over QC45.', date: 'Mar 3, 2025' },
    ],
    relatedIds: ['bose-qc45', 'bose-nc700'],
  },
  {
    id: 'plantronics-backbeat',
    name: 'BackBeat Pro 2',
    brand: 'Poly',
    category: 'Headphones',
    price: 79,
    originalPrice: 199,
    rating: 4.1,
    reviewCount: 3421,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Feature-packed wireless ANC headphones with sensor-based smart controls. 22-hour battery with DeepSleep mode extending standby to 6 months.',
    specs: [
      { label: 'Battery life', value: '22 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 4.1, NFC, 3.5mm' },
      { label: 'Weight', value: '283 g' },
      { label: 'Sensors', value: 'Proximity + accelerometer' },
    ],
    reviews: [
      { id: 'r1', author: 'Blake N.', rating: 4, comment: 'Great deal at this clearance price. Solid ANC and smart sensors work well.', date: 'Feb 20, 2025' },
      { id: 'r2', author: 'Cora A.', rating: 4, comment: 'Comfortable and feature rich. ANC is decent for older tech.', date: 'Jan 8, 2025' },
    ],
    relatedIds: ['jabra-evolve2-65', 'anker-q45'],
  },
  {
    id: 'creative-aurvana',
    name: 'Aurvana Ace 2',
    brand: 'Creative',
    category: 'Headphones',
    price: 149,
    rating: 4.3,
    reviewCount: 876,
    stock: 'in_stock',
    badge: 'new',
    description: 'Wireless ANC earphones with 13.6mm xMEMS Skyline drivers and 30dB adaptive ANC. Crystal-clear spatial audio and mimi Health hearing personalization.',
    specs: [
      { label: 'Driver', value: '13.6mm xMEMS Skyline' },
      { label: 'Battery life', value: '6 hrs (buds) + 20 hrs (case)' },
      { label: 'Connectivity', value: 'Bluetooth 5.3' },
      { label: 'Weight', value: '6 g per bud' },
      { label: 'ANC', value: '30dB adaptive' },
    ],
    reviews: [
      { id: 'r1', author: 'Lucy W.', rating: 5, comment: 'xMEMS drivers are the future. Details I never heard before on familiar tracks.', date: 'Mar 14, 2025' },
      { id: 'r2', author: 'Hugo T.', rating: 4, comment: 'Impressive tech in a small package. The ANC is very strong.', date: 'Feb 6, 2025' },
    ],
    relatedIds: ['anker-q45', 'jbl-live770'],
  },
  {
    id: 'technics-eah-a800',
    name: 'EAH-A800',
    brand: 'Technics',
    category: 'Headphones',
    price: 299,
    originalPrice: 349,
    rating: 4.6,
    reviewCount: 954,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Premium wireless headphones with Technics JustMyVoice microphone technology and dual action ANC. 50-hour battery with fast charging and multipoint Bluetooth.',
    specs: [
      { label: 'Driver size', value: '40mm (PEEK diaphragm)' },
      { label: 'Battery life', value: '50 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.2, USB-C, 3.5mm' },
      { label: 'Weight', value: '265 g' },
      { label: 'Multipoint', value: '2 devices' },
    ],
    reviews: [
      { id: 'r1', author: 'Kenji M.', rating: 5, comment: 'Technics audio quality never disappoints. The 50-hour battery is a huge bonus.', date: 'Mar 7, 2025' },
      { id: 'r2', author: 'Amanda K.', rating: 4, comment: 'Excellent sound and build quality. Understated compared to Sony but possibly better-tuned.', date: 'Feb 1, 2025' },
    ],
    relatedIds: ['sennheiser-momentum4', 'bose-qc-ultra'],
  },
  {
    id: 'nuraphone',
    name: 'Nuraphone',
    brand: 'Nura',
    category: 'Headphones',
    price: 249,
    originalPrice: 399,
    rating: 4.4,
    reviewCount: 1432,
    stock: 'out_of_stock',
    badge: 'sale',
    description: 'Unique in-ear + over-ear design that learns and adapts to your personal hearing profile using otoacoustic emissions. No EQ — it personalizes to you automatically.',
    specs: [
      { label: 'Driver', value: 'Hybrid in-ear + over-ear' },
      { label: 'Battery life', value: '20 hrs' },
      { label: 'Connectivity', value: 'Bluetooth 4.2, 3.5mm' },
      { label: 'Weight', value: '355 g' },
      { label: 'Personalization', value: 'Automatic via app' },
    ],
    reviews: [
      { id: 'r1', author: 'Claire H.', rating: 5, comment: 'The most unique headphone experience. Once personalized, everything sounds perfectly tailored.', date: 'Jan 25, 2025' },
      { id: 'r2', author: 'Simon B.', rating: 4, comment: 'Weird looking but the personalization technology is real. Tracks I thought I knew sound new.', date: 'Dec 15, 2024' },
    ],
    relatedIds: ['bose-qc-ultra', 'sennheiser-momentum4'],
  },
  {
    id: 'anker-soundcore-a3',
    name: 'Soundcore Space Q45',
    brand: 'Anker',
    category: 'Headphones',
    price: 79,
    originalPrice: 99,
    rating: 4.4,
    reviewCount: 14321,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Adaptive active noise cancellation that auto-adjusts to your environment. Up to 65 hours battery, LDAC Hi-Res wireless, and foldable travel design.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Battery life', value: '50 hrs (ANC on), 65 hrs (ANC off)' },
      { label: 'Connectivity', value: 'Bluetooth 5.3, 3.5mm' },
      { label: 'Codec', value: 'LDAC, AAC, SBC' },
      { label: 'ANC', value: 'Adaptive multi-mode' },
    ],
    reviews: [
      { id: 'r1', author: 'Tyler S.', rating: 5, comment: 'Best sub-$100 ANC headphones. 65-hour battery and LDAC at this price is insane.', date: 'Mar 20, 2025' },
      { id: 'r2', author: 'Nina V.', rating: 4, comment: 'Excellent value. Sound quality rivals headphones 3x the price.', date: 'Feb 14, 2025' },
    ],
    relatedIds: ['anker-q45', 'anker-q35'],
  },
  {
    id: 'edifier-wh950nb',
    name: 'WH950NB',
    brand: 'Edifier',
    category: 'Headphones',
    price: 99,
    originalPrice: 149,
    rating: 4.3,
    reviewCount: 2109,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Hybrid ANC wireless headphones with LDAC codec, 48-hour battery, and multipoint Bluetooth connection. Hi-Res Audio wireless certified.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Battery life', value: '48 hrs (ANC off)' },
      { label: 'Connectivity', value: 'Bluetooth 5.3, 3.5mm' },
      { label: 'Codec', value: 'LDAC, aptX' },
      { label: 'ANC', value: 'Hybrid feed-forward + feedback' },
    ],
    reviews: [
      { id: 'r1', author: 'Wei L.', rating: 4, comment: 'LDAC and 48-hour battery under $100. Edifier is seriously competing now.', date: 'Mar 13, 2025' },
      { id: 'r2', author: 'Anna S.', rating: 4, comment: 'Good ANC and sound quality. Build feels premium for the price.', date: 'Feb 5, 2025' },
    ],
    relatedIds: ['anker-q45', 'jbl-live660'],
  },
  {
    id: 'microsoft-surface-headphones2',
    name: 'Surface Headphones 2+',
    brand: 'Microsoft',
    category: 'Headphones',
    price: 199,
    originalPrice: 249,
    rating: 4.3,
    reviewCount: 1876,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Wireless headphones optimized for Microsoft Teams with dedicated Teams button. 13 levels of on-ear ANC controls and 30-hour battery. Works seamlessly with Surface devices.',
    specs: [
      { label: 'Battery life', value: '30 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.0, 3.5mm' },
      { label: 'Weight', value: '290 g' },
      { label: 'ANC levels', value: '13 on-ear dial' },
      { label: 'Integration', value: 'Microsoft Teams button' },
    ],
    reviews: [
      { id: 'r1', author: 'Helen G.', rating: 4, comment: 'Best headphones for Microsoft 365 users. Teams integration is flawless.', date: 'Feb 28, 2025' },
      { id: 'r2', author: 'Greg P.', rating: 4, comment: 'Solid work headphones. The on-ear dial for ANC is a clever design.', date: 'Jan 18, 2025' },
    ],
    relatedIds: ['jabra-evolve2-65', 'plantronics-voyager'],
  },
  {
    id: 'hifiman-sundara',
    name: 'Sundara',
    brand: 'HiFiMAN',
    category: 'Headphones',
    price: 299,
    rating: 4.8,
    reviewCount: 2341,
    stock: 'in_stock',
    badge: null,
    description: 'Planar magnetic headphones with high-quality diaphragm and advanced asymmetrical magnetic circuit. Exceptional detail and imaging for audiophile listening.',
    specs: [
      { label: 'Driver', value: 'Planar magnetic' },
      { label: 'Impedance', value: '37 Ω' },
      { label: 'Frequency response', value: '6 Hz – 75,000 Hz' },
      { label: 'Connectivity', value: '3.5mm, dual 3.5mm' },
      { label: 'Type', value: 'Open-back, wired' },
    ],
    reviews: [
      { id: 'r1', author: 'Alex T.', rating: 5, comment: 'Best planar magnetic under $400. The Sundara is legendary for good reason.', date: 'Mar 15, 2025' },
      { id: 'r2', author: 'Petra M.', rating: 5, comment: 'Imaging is extraordinary. Every instrument has a precise location in the soundstage.', date: 'Feb 8, 2025' },
    ],
    relatedIds: ['sennheiser-hd660s2', 'beyerdynamic-dt900'],
  },
  {
    id: 'hifiman-ananda',
    name: 'Ananda',
    brand: 'HiFiMAN',
    category: 'Headphones',
    price: 499,
    originalPrice: 699,
    rating: 4.7,
    reviewCount: 1234,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Premium planar magnetic open-back headphones with Window Shade system for excellent venting. Single-sided magnet design with super-nano diaphragm.',
    specs: [
      { label: 'Driver', value: 'Planar magnetic (super-nano diaphragm)' },
      { label: 'Impedance', value: '25 Ω' },
      { label: 'Frequency response', value: '8 Hz – 55,000 Hz' },
      { label: 'Connectivity', value: '3.5mm, 6.35mm' },
      { label: 'Type', value: 'Open-back, wired' },
    ],
    reviews: [
      { id: 'r1', author: 'Richard F.', rating: 5, comment: 'The Ananda is a giant-killer. It embarrasses dynamic driver headphones costing twice as much.', date: 'Mar 5, 2025' },
      { id: 'r2', author: 'Camille N.', rating: 5, comment: 'Huge soundstage and exceptional detail retrieval. My endgame open-back.', date: 'Feb 1, 2025' },
    ],
    relatedIds: ['hifiman-sundara', 'ath-adx5000'],
  },
  {
    id: 'focal-listen',
    name: 'Listen Wireless Chic',
    brand: 'Focal',
    category: 'Headphones',
    price: 199,
    rating: 4.5,
    reviewCount: 621,
    stock: 'in_stock',
    badge: null,
    description: 'French-designed wireless headphones with Focal acoustic expertise. Full-range 40mm mylar drivers with neodymium magnets and 20-hour battery in a compact foldable form.',
    specs: [
      { label: 'Driver', value: '40mm mylar' },
      { label: 'Battery life', value: '20 hrs' },
      { label: 'Connectivity', value: 'Bluetooth 4.2, 3.5mm' },
      { label: 'Weight', value: '218 g' },
      { label: 'Origin', value: 'Designed in France' },
    ],
    reviews: [
      { id: 'r1', author: 'Marc D.', rating: 5, comment: 'Focal sound quality in a portable package. The French know audio.', date: 'Feb 19, 2025' },
      { id: 'r2', author: 'Amelie B.', rating: 4, comment: 'Beautiful and great sounding. Wish it had ANC at this price.', date: 'Jan 22, 2025' },
    ],
    relatedIds: ['sennheiser-momentum4', 'shure-aonic50'],
  },
  {
    id: 'meze-99-classics',
    name: '99 Classics',
    brand: 'Meze',
    category: 'Headphones',
    price: 309,
    rating: 4.7,
    reviewCount: 1087,
    stock: 'in_stock',
    badge: null,
    description: 'Handcrafted headphones with walnut wood ear cups and self-adjusting headband. 40mm drivers deliver a warm, rich sound signature beloved by audiophiles.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Impedance', value: '32 Ω' },
      { label: 'Frequency response', value: '15 Hz – 25,000 Hz' },
      { label: 'Connectivity', value: '3.5mm (detachable)' },
      { label: 'Materials', value: 'Walnut wood, zinc alloy' },
    ],
    reviews: [
      { id: 'r1', author: 'Pavel K.', rating: 5, comment: 'The most beautiful headphones I own. Sound is warm, detailed, and musical.', date: 'Mar 11, 2025' },
      { id: 'r2', author: 'Lily R.', rating: 5, comment: 'Walnut wood cups are gorgeous and the self-adjusting band fits every head perfectly.', date: 'Feb 4, 2025' },
    ],
    relatedIds: ['focal-listen', 'sennheiser-hd660s2'],
  },
  {
    id: 'pioneer-hdj-x7',
    name: 'HDJ-X7',
    brand: 'Pioneer DJ',
    category: 'Headphones',
    price: 199,
    rating: 4.6,
    reviewCount: 1432,
    stock: 'in_stock',
    badge: null,
    description: 'Professional DJ headphones with 50mm Hi-X drivers for minimal distortion and maximum clarity. Dual-sided or single-sided cable connection with 270° swivel cups.',
    specs: [
      { label: 'Driver size', value: '50mm' },
      { label: 'Frequency response', value: '5 Hz – 40,000 Hz' },
      { label: 'Impedance', value: '32 Ω' },
      { label: 'Connectivity', value: '3.5mm + 6.35mm adapter' },
      { label: 'Swivel', value: '270°' },
    ],
    reviews: [
      { id: 'r1', author: 'DJ Kira', rating: 5, comment: 'The reference standard for DJ monitoring. Uncolored and punchy.', date: 'Mar 18, 2025' },
      { id: 'r2', author: 'Max R.', rating: 5, comment: 'Built like a tank and sounds incredible. My go-to for festivals.', date: 'Feb 14, 2025' },
    ],
    relatedIds: ['audio-technica-ath-dj', 'beyerdynamic-dt770'],
  },
  {
    id: 'audio-technica-ath-dj',
    name: 'ATH-M70x',
    brand: 'Audio-Technica',
    category: 'Headphones',
    price: 249,
    rating: 4.8,
    reviewCount: 876,
    stock: 'in_stock',
    badge: null,
    description: 'Professional studio monitor headphones with wide 5Hz-40kHz response for Hi-Res Audio. Same chassis as ATH-M50x with improved transducers and replaceable cables.',
    specs: [
      { label: 'Driver size', value: '45mm' },
      { label: 'Frequency response', value: '5 Hz – 40,000 Hz' },
      { label: 'Impedance', value: '35 Ω' },
      { label: 'Connectivity', value: '3.5mm (detachable, 3 cables)' },
      { label: 'Type', value: 'Closed-back, wired' },
    ],
    reviews: [
      { id: 'r1', author: 'Phil N.', rating: 5, comment: 'The big brother of the M50x. More analytical and detailed.', date: 'Mar 6, 2025' },
      { id: 'r2', author: 'Angela W.', rating: 5, comment: 'My mastering reference. Completely flat response, no flattery.', date: 'Jan 28, 2025' },
    ],
    relatedIds: ['ath-m50x', 'ath-m40x'],
  },
  {
    id: 'sennheiser-hd560s',
    name: 'HD 560S',
    brand: 'Sennheiser',
    category: 'Headphones',
    price: 149,
    rating: 4.7,
    reviewCount: 2341,
    stock: 'in_stock',
    badge: null,
    description: 'Open-back audiophile headphones for neutral and accurate listening. Angled transducers improve spatial performance and reduce reflections inside the ear cup.',
    specs: [
      { label: 'Driver size', value: '38mm (angled)' },
      { label: 'Impedance', value: '120 Ω' },
      { label: 'Frequency response', value: '6 Hz – 38,000 Hz' },
      { label: 'Connectivity', value: '6.35mm' },
      { label: 'Type', value: 'Open-back, wired' },
    ],
    reviews: [
      { id: 'r1', author: 'George F.', rating: 5, comment: 'Best open-back under $200 by a mile. Neutral and wide soundstage.', date: 'Mar 22, 2025' },
      { id: 'r2', author: 'Clara M.', rating: 5, comment: 'The angled transducers really work. Imaging is wider than expected.', date: 'Feb 14, 2025' },
    ],
    relatedIds: ['sennheiser-hd660s2', 'hifiman-sundara'],
  },
  {
    id: 'denon-ah-gc30',
    name: 'AH-GC30',
    brand: 'Denon',
    category: 'Headphones',
    price: 149,
    originalPrice: 299,
    rating: 4.2,
    reviewCount: 876,
    stock: 'in_stock',
    badge: 'sale',
    description: 'Wireless ANC headphones with Hi-Res Audio and Denon acoustic engineering. Advanced ANC removes low-frequency drone for travel and commuting.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Battery life', value: '20 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 4.2, 3.5mm' },
      { label: 'Weight', value: '275 g' },
      { label: 'Hi-Res', value: 'Certified (wired)' },
    ],
    reviews: [
      { id: 'r1', author: 'Dan S.', rating: 4, comment: 'Excellent deal at this price. Denon tuning is musical and smooth.', date: 'Feb 9, 2025' },
      { id: 'r2', author: 'Fiona T.', rating: 4, comment: 'Good ANC and Hi-Res capability. A bit outdated but still performs.', date: 'Jan 5, 2025' },
    ],
    relatedIds: ['sony-wh1000xm4', 'anker-q45'],
  },
  {
    id: 'jlab-studio-anc',
    name: 'Studio ANC Wireless',
    brand: 'JLab',
    category: 'Headphones',
    price: 29,
    rating: 4.1,
    reviewCount: 11234,
    stock: 'in_stock',
    badge: 'bestseller',
    description: 'Budget ANC wireless headphones with 45-hour battery and built-in EQ (Signature, Balanced, Bass Boost). The most affordable ANC headphones that actually work.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Battery life', value: '45 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.1, 3.5mm' },
      { label: 'Weight', value: '210 g' },
      { label: 'ANC', value: 'Active noise cancellation' },
    ],
    reviews: [
      { id: 'r1', author: 'Amy C.', rating: 4, comment: 'I cannot believe these cost $29. ANC actually works well for blocking out noise.', date: 'Mar 28, 2025' },
      { id: 'r2', author: 'Brian H.', rating: 4, comment: 'Perfect for students and casual use. Value per dollar is astronomical.', date: 'Mar 1, 2025' },
    ],
    relatedIds: ['anker-q35', 'skullcandy-hesh-evo'],
  },
  {
    id: 'taotronics-tt-bh090',
    name: 'SoundSurge 90',
    brand: 'TaoTronics',
    category: 'Headphones',
    price: 49,
    rating: 4.2,
    reviewCount: 8321,
    stock: 'in_stock',
    badge: null,
    description: 'Hybrid active noise cancellation headphones with cVc 8.0 microphone technology. Transparency mode, 30-hour battery, and memory foam ear cushions for comfort.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Battery life', value: '30 hrs (ANC on)' },
      { label: 'Connectivity', value: 'Bluetooth 5.0, 3.5mm' },
      { label: 'Weight', value: '250 g' },
      { label: 'Mic', value: 'cVc 8.0 noise reduction' },
    ],
    reviews: [
      { id: 'r1', author: 'Steve R.', rating: 4, comment: 'Excellent budget ANC. Memory foam is very comfortable.', date: 'Feb 22, 2025' },
      { id: 'r2', author: 'Mary T.', rating: 4, comment: 'Good for the price. ANC works well in offices and on planes.', date: 'Jan 15, 2025' },
    ],
    relatedIds: ['anker-q35', 'jlab-studio-anc'],
  },
  {
    id: 'sony-wh-ch510',
    name: 'WH-CH510',
    brand: 'Sony',
    category: 'Headphones',
    price: 39,
    rating: 4.1,
    reviewCount: 21087,
    stock: 'in_stock',
    badge: null,
    description: 'Entry-level wireless headphones with 35-hour battery life. Folding design and lightweight 132g body. Hands-free calling with built-in microphone and Google Fast Pair.',
    specs: [
      { label: 'Battery life', value: '35 hrs' },
      { label: 'Connectivity', value: 'Bluetooth 5.0, 3.5mm' },
      { label: 'Weight', value: '132 g' },
      { label: 'Fast Pair', value: 'Google Fast Pair' },
    ],
    reviews: [
      { id: 'r1', author: 'Linda P.', rating: 4, comment: 'Simple, lightweight and reliable. Perfect for gym and casual use.', date: 'Mar 5, 2025' },
      { id: 'r2', author: 'Carlos M.', rating: 4, comment: '35 hours at $39 is incredible. Sony quality control as always.', date: 'Feb 8, 2025' },
    ],
    relatedIds: ['sony-wh-ch720n', 'jlab-studio-anc'],
  },
  {
    id: 'sennheiser-hd-350bt',
    name: 'HD 350BT',
    brand: 'Sennheiser',
    category: 'Headphones',
    price: 79,
    rating: 4.3,
    reviewCount: 4321,
    stock: 'in_stock',
    badge: null,
    description: 'Entry-level wireless headphones with Sennheiser sound tuning, AAC & aptX support, and 30-hour battery. Bass-boosted sound with foldable design and USB-C charging.',
    specs: [
      { label: 'Driver size', value: '32mm' },
      { label: 'Battery life', value: '30 hrs' },
      { label: 'Connectivity', value: 'Bluetooth 5.0, USB-C' },
      { label: 'Codec', value: 'aptX, AAC' },
      { label: 'Weight', value: '165 g' },
    ],
    reviews: [
      { id: 'r1', author: 'Patrick D.', rating: 4, comment: 'Best sub-$100 wireless headphones. Sennheiser quality at an accessible price.', date: 'Mar 15, 2025' },
      { id: 'r2', author: 'Sara A.', rating: 4, comment: 'Clear sound and easy pairing. Great starter headphones.', date: 'Feb 11, 2025' },
    ],
    relatedIds: ['sennheiser-momentum4', 'anker-q35'],
  },
  {
    id: 'koss-portapro',
    name: 'Porta Pro',
    brand: 'Koss',
    category: 'Headphones',
    price: 39,
    rating: 4.5,
    reviewCount: 34521,
    stock: 'in_stock',
    badge: 'bestseller',
    description: 'Legendary on-ear headphones with temporal pad comfort system. Introduced in 1984 and unchanged because the sound is that good. Foldable and repairable for a lifetime.',
    specs: [
      { label: 'Driver size', value: '60mm' },
      { label: 'Frequency response', value: '15 Hz – 25,000 Hz' },
      { label: 'Impedance', value: '60 Ω' },
      { label: 'Connectivity', value: '3.5mm' },
      { label: 'Weight', value: '60 g' },
    ],
    reviews: [
      { id: 'r1', author: 'Tom R.', rating: 5, comment: 'These have been on sale for 40 years because they are that good. Legend.', date: 'Mar 25, 2025' },
      { id: 'r2', author: 'Joan C.', rating: 5, comment: 'I have replaced the pads and foam twice. Worth repairing forever.', date: 'Feb 19, 2025' },
    ],
    relatedIds: ['ath-m40x', 'marshall-major5'],
  },
  {
    id: 'grado-sr80x',
    name: 'SR80x',
    brand: 'Grado',
    category: 'Headphones',
    price: 149,
    rating: 4.6,
    reviewCount: 2109,
    stock: 'in_stock',
    badge: null,
    description: 'Open-back dynamic headphones handmade in Brooklyn. The Prestige Series X driver brings improved transient response and reduced distortion over the previous generation.',
    specs: [
      { label: 'Driver', value: 'X series dynamic' },
      { label: 'Impedance', value: '38 Ω' },
      { label: 'Frequency response', value: '20 Hz – 20,000 Hz' },
      { label: 'Connectivity', value: '3.5mm' },
      { label: 'Origin', value: 'Handmade in Brooklyn, NY' },
    ],
    reviews: [
      { id: 'r1', author: 'Victor M.', rating: 5, comment: 'Nothing sounds like a Grado. Raw, live, energetic presentation. Rock music nirvana.', date: 'Mar 18, 2025' },
      { id: 'r2', author: 'Ruth B.', rating: 5, comment: 'Handmade quality at an accessible price. The energy and detail is unmatched.', date: 'Feb 5, 2025' },
    ],
    relatedIds: ['sennheiser-hd560s', 'hifiman-sundara'],
  },
  {
    id: 'audio-technica-ath-r70x',
    name: 'ATH-R70x',
    brand: 'Audio-Technica',
    category: 'Headphones',
    price: 299,
    rating: 4.8,
    reviewCount: 876,
    stock: 'in_stock',
    badge: null,
    description: 'Pure open-back reference headphones designed for studio mixing and mastering. Exceptionally accurate, true-to-source sound with self-adjusting 3D wing support.',
    specs: [
      { label: 'Driver size', value: '45mm' },
      { label: 'Impedance', value: '470 Ω' },
      { label: 'Frequency response', value: '5 Hz – 40,000 Hz' },
      { label: 'Connectivity', value: '3.5mm + 6.35mm adapter' },
      { label: 'Type', value: 'Open-back, wired' },
    ],
    reviews: [
      { id: 'r1', author: 'Chris J.', rating: 5, comment: 'AT mastering reference headphones. Accurate, detailed, and very comfortable.', date: 'Mar 4, 2025' },
      { id: 'r2', author: 'Diana S.', rating: 5, comment: 'After 470 Ω these need a good amp but they reward accordingly.', date: 'Feb 1, 2025' },
    ],
    relatedIds: ['ath-m50x', 'beyerdynamic-dt900'],
  },
  {
    id: 'oneodio-monitor60',
    name: 'Monitor 60',
    brand: 'OneOdio',
    category: 'Headphones',
    price: 49,
    rating: 4.3,
    reviewCount: 15234,
    stock: 'in_stock',
    badge: null,
    description: 'Professional studio monitor headphones with 50mm neodymium drivers and 110dB sensitivity. Dual 3.5mm and 6.35mm jack for direct connection to most devices.',
    specs: [
      { label: 'Driver size', value: '50mm' },
      { label: 'Impedance', value: '32 Ω' },
      { label: 'Frequency response', value: '20 Hz – 20,000 Hz' },
      { label: 'Connectivity', value: '3.5mm + 6.35mm (detachable)' },
      { label: 'Type', value: 'Closed-back, wired' },
    ],
    reviews: [
      { id: 'r1', author: 'Dennis T.', rating: 4, comment: 'Great budget monitor headphones. Better sound than the price suggests.', date: 'Mar 12, 2025' },
      { id: 'r2', author: 'Kim L.', rating: 4, comment: 'Used for bedroom production. Solid value for beginners.', date: 'Feb 8, 2025' },
    ],
    relatedIds: ['ath-m40x', 'shure-srh840a'],
  },
  {
    id: 'audio-technica-ath-m20x',
    name: 'ATH-M20x',
    brand: 'Audio-Technica',
    category: 'Headphones',
    price: 49,
    rating: 4.3,
    reviewCount: 18921,
    stock: 'in_stock',
    badge: null,
    description: 'Entry-level studio monitor headphones with 40mm drivers tuned for critical listening. Contoured ear cups with professional earpads for long sessions.',
    specs: [
      { label: 'Driver size', value: '40mm' },
      { label: 'Frequency response', value: '15 Hz – 20,000 Hz' },
      { label: 'Impedance', value: '47 Ω' },
      { label: 'Connectivity', value: '3.5mm + 6.35mm adapter' },
      { label: 'Type', value: 'Closed-back, wired' },
    ],
    reviews: [
      { id: 'r1', author: 'Will D.', rating: 4, comment: 'Perfect entry into studio monitoring. Better than consumer headphones for mixing.', date: 'Mar 9, 2025' },
      { id: 'r2', author: 'Sasha P.', rating: 4, comment: 'Bought as a first studio headphone and I am very happy.', date: 'Feb 3, 2025' },
    ],
    relatedIds: ['ath-m40x', 'ath-m50x'],
  },
  // ── End Additional Headphones ──────────────────────────────────────────────
  {
    id: 'mx-keys-s',
    name: 'MX Keys S',
    brand: 'Logitech',
    category: 'Keyboards',
    price: 109,
    originalPrice: 129,
    rating: 4.5,
    reviewCount: 3104,
    stock: 'in_stock',
    badge: 'sale',
    description:
      'Advanced wireless keyboard with smart backlighting that adjusts to your ambient light. Spherically dished keys perfectly match your fingertips for a satisfying, precise typing experience.',
    specs: [
      { label: 'Switch type', value: 'Scissor (low-profile)' },
      { label: 'Connectivity', value: 'Bluetooth 5, USB receiver' },
      { label: 'Battery life', value: 'Up to 10 days (backlit)' },
      { label: 'Multi-device', value: 'Up to 3 devices' },
      { label: 'Backlight', value: 'Smart adaptive' },
      { label: 'Layout', value: 'Full-size, US ANSI' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Tom W.',
        rating: 5,
        comment: 'Best typing experience on a wireless keyboard. The key feel is incredibly satisfying and it pairs across 3 devices seamlessly.',
        date: 'Mar 22, 2025',
      },
      {
        id: 'r2',
        author: 'Aisha B.',
        rating: 4,
        comment: 'Great keyboard for the price. The smart backlighting is a nice touch. Wish the battery lasted longer.',
        date: 'Feb 27, 2025',
      },
    ],
    relatedIds: ['keychron-q1', 'ducky-one-3'],
  },
  {
    id: 'keychron-q1',
    name: 'Q1 Pro',
    brand: 'Keychron',
    category: 'Keyboards',
    price: 199,
    rating: 4.9,
    reviewCount: 1487,
    stock: 'low_stock',
    badge: 'new',
    description:
      'Fully customizable wireless mechanical keyboard with a solid aluminum body. Hot-swappable Gateron G Pro switches, QMK/VIA support, and a gasket-mounted plate for premium typing sound.',
    specs: [
      { label: 'Switch type', value: 'Gateron G Pro Red (hot-swap)' },
      { label: 'Connectivity', value: 'Bluetooth 5.1, USB-C' },
      { label: 'Battery life', value: 'Up to 4000 mAh' },
      { label: 'Body material', value: 'CNC aluminum' },
      { label: 'Firmware', value: 'QMK / VIA' },
      { label: 'Layout', value: '75%, US ANSI' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Ryan H.',
        rating: 5,
        comment: 'This is my endgame keyboard. The thock is real and QMK support is a game-changer for customization.',
        date: 'Mar 30, 2025',
      },
      {
        id: 'r2',
        author: 'Fatima N.',
        rating: 5,
        comment: 'Premium feel in every way. The aluminum body makes it feel like a $400 board. Stock switches are great too.',
        date: 'Mar 1, 2025',
      },
    ],
    relatedIds: ['mx-keys-s', 'ducky-one-3'],
  },
  {
    id: 'ducky-one-3',
    name: 'One 3 TKL',
    brand: 'Ducky',
    category: 'Keyboards',
    price: 109,
    rating: 4.6,
    reviewCount: 892,
    stock: 'in_stock',
    badge: null,
    description:
      'Tenkeyless mechanical keyboard with hot-swappable PCB, per-key RGB, and triple-layer sound dampening foam. Compatible with MX-style switches and PBT double-shot keycaps.',
    specs: [
      { label: 'Switch type', value: 'Cherry MX Red (hot-swap)' },
      { label: 'Connectivity', value: 'USB-C (detachable)' },
      { label: 'RGB', value: 'Per-key RGB' },
      { label: 'Keycaps', value: 'PBT double-shot' },
      { label: 'Sound foam', value: 'Triple-layer dampening' },
      { label: 'Layout', value: 'TKL, US ANSI' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Lena P.',
        rating: 5,
        comment: 'Incredible value. The typing sound is better than boards twice the price.',
        date: 'Feb 19, 2025',
      },
    ],
    relatedIds: ['keychron-q1', 'mx-keys-s'],
  },
  {
    id: 'lg-27gp850',
    name: '27GP850-B',
    brand: 'LG',
    category: 'Monitors',
    price: 349,
    originalPrice: 449,
    rating: 4.7,
    reviewCount: 2198,
    stock: 'in_stock',
    badge: 'sale',
    description:
      '27-inch QHD Nano IPS panel with 165Hz refresh rate and 1ms response time. G-Sync compatible with HDR400 support, ideal for competitive gaming and creative work.',
    specs: [
      { label: 'Panel', value: 'Nano IPS' },
      { label: 'Resolution', value: '2560 × 1440 (QHD)' },
      { label: 'Refresh rate', value: '165 Hz (OC to 180 Hz)' },
      { label: 'Response time', value: '1ms (GtG)' },
      { label: 'HDR', value: 'VESA DisplayHDR 400' },
      { label: 'Ports', value: 'HDMI 2.0 ×2, DP 1.4 ×1' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Kai S.',
        rating: 5,
        comment: 'Stunning colors for a gaming monitor. The Nano IPS makes a huge difference compared to regular IPS at this price.',
        date: 'Mar 14, 2025',
      },
      {
        id: 'r2',
        author: 'Olga M.',
        rating: 4,
        comment: 'Great monitor overall. Colors are vivid and the 165Hz is very smooth. The stand could be better.',
        date: 'Jan 29, 2025',
      },
    ],
    relatedIds: ['samsung-odyssey-g7', 'dell-u2723d'],
  },
  {
    id: 'samsung-odyssey-g7',
    name: 'Odyssey G7 27"',
    brand: 'Samsung',
    category: 'Monitors',
    price: 499,
    rating: 4.5,
    reviewCount: 1643,
    stock: 'in_stock',
    badge: 'bestseller',
    description:
      '27-inch curved QLED gaming monitor with 240Hz refresh rate and 1ms response time. 1000R curvature wraps around your field of view for an immersive gaming experience.',
    specs: [
      { label: 'Panel', value: 'VA (QLED)' },
      { label: 'Resolution', value: '2560 × 1440 (QHD)' },
      { label: 'Refresh rate', value: '240 Hz' },
      { label: 'Response time', value: '1ms (MPRT)' },
      { label: 'Curvature', value: '1000R' },
      { label: 'HDR', value: 'VESA DisplayHDR 600' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Marco R.',
        rating: 5,
        comment: 'The 240Hz curve is insane for FPS games. Colors pop and the curve feels natural, not gimmicky.',
        date: 'Mar 2, 2025',
      },
      {
        id: 'r2',
        author: 'Diane C.',
        rating: 4,
        comment: 'Excellent gaming monitor. VA panel has better contrast than IPS. Minor ghosting in very dark scenes.',
        date: 'Feb 8, 2025',
      },
    ],
    relatedIds: ['lg-27gp850', 'dell-u2723d'],
  },
  {
    id: 'dell-u2723d',
    name: 'UltraSharp U2723D',
    brand: 'Dell',
    category: 'Monitors',
    price: 589,
    rating: 4.8,
    reviewCount: 976,
    stock: 'low_stock',
    badge: 'new',
    description:
      '27-inch 4K IPS Black panel monitor with exceptional color accuracy (100% sRGB, 98% DCI-P3). Designed for creative professionals who demand precision.',
    specs: [
      { label: 'Panel', value: 'IPS Black' },
      { label: 'Resolution', value: '3840 × 2160 (4K UHD)' },
      { label: 'Refresh rate', value: '60 Hz' },
      { label: 'Color coverage', value: '100% sRGB, 98% DCI-P3' },
      { label: 'HDR', value: 'VESA DisplayHDR 400' },
      { label: 'Ports', value: 'Thunderbolt 4, USB-C, HDMI, DP' },
    ],
    reviews: [
      {
        id: 'r1',
        author: 'Elena W.',
        rating: 5,
        comment: 'Perfect for photo and video editing. The color accuracy out of the box is incredible. Every designer needs this.',
        date: 'Mar 25, 2025',
      },
      {
        id: 'r2',
        author: 'James F.',
        rating: 5,
        comment: 'IPS Black panel is a revelation. The contrast ratio destroys regular IPS at this price range.',
        date: 'Mar 10, 2025',
      },
    ],
    relatedIds: ['lg-27gp850', 'samsung-odyssey-g7'],
  },
]

export const categories: Category[] = ['Headphones', 'Keyboards', 'Monitors']
